myapp/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views


urlpatterns =[
    path('', views.home, name='home'),
    path('home', views.home, name='about'),
    path('categories/', views.category_list, name='category_list'),
    path('category_recipes/<int:category_id>/', views.category_recipes, name='category_recipes'),
    path('recipe_details/<int:recipe_id>/', views.recipe_details, name='recipe_details'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('registration/', views.register_chef, name='register_chef'),
    path('add_recipe/', views.add_recipe, name='add_recipe'),
    path('add_product_to_recipe/<int:post_id>/', views.add_product_to_recipe, name='add_product_to_recipe'),
    path('add_steps_to_recipe/<int:post_id>/', views.add_steps_to_recipe, name='add_steps_to_recipe'),
    path('chef_recipes/<int:chef_id>/', views.chef_recipes, name='chef_recipes'),
    path('my_recipes/', views.my_recipes, name='my_recipes'),
    path('all_recipes/', views.all_recipes, name='all_recipes'),
    path('edit_recipe/<int:recipe_id>/', views.edit_recipe, name='edit_recipe'),
    path('recipe_detail/<int:recipe_id>/', views.recipe_detail, name='recipe_detail'),
]

recipes_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("myapp.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import migrations, models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
from django.db.models.signals import pre_save
from django.dispatch import receiver
import uuid


class Chef(AbstractUser):
    username = models.CharField(max_length=20, unique=True)
    nick_name = models.CharField(max_length=20)
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=11)
    about_me = models.TextField()
    register_date = models.DateTimeField(auto_now=True)
    USERNAME_FIELD = 'username'

@receiver(pre_save, sender=Chef)
def generate_unique_username(sender, instance, **kwargs):
    if not instance.username:
        current_time = timezone.now().strftime('%Y%m%d%H%M%S')
        random_uuid = str(uuid.uuid4().hex)[:5]
        instance.username = f'user_{current_time}_{random_uuid}'


class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()


class Post(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    cooking_time = models.DecimalField(max_digits=10, decimal_places=2)
    images = models.ImageField(upload_to='media/', null=True, blank=True)
    register_date = models.DateTimeField(auto_now=True)
    chef_id = models.ForeignKey(Chef, on_delete=models.SET('Анонимный шеф-повар'))
    category_id = models.ForeignKey(Category, on_delete=models.SET('Вне категорий'))
    product_id = models.ManyToManyField(Product)


class CookingStep(models.Model):
    post_id = models.ForeignKey(Post, on_delete=models.CASCADE, default=1)
    description = models.TextField()
    images = models.ImageField(upload_to='dish_images/', null=True, blank=True)


class ProductQuantity(models.Model):
    KG = 'кг'
    LITR = 'литр'
    GRAMM = 'грамм'
    TABLESPOON = 'столовая ложка'
    GLASS = 'стакан'
    TEASPOON = 'чайная ложка'

    MEASUREMENT_CHOICES = [
        (KG, 'килограмм'),
        (LITR, 'литр'),
        (GRAMM, 'грамм'),
        (TABLESPOON, 'столовая ложка'),
        (GLASS, 'стакан'),
        (TEASPOON, 'чайная ложка'),
    ]

    product_id = models.ForeignKey(Product, on_delete=models.CASCADE)
    post_id = models.ForeignKey(Post, on_delete=models.CASCADE, default=1)
    count = models.DecimalField(max_digits=10, decimal_places=2)
    measurement = models.CharField(max_length=20, choices=MEASUREMENT_CHOICES)

myapp/forms.py
from django import forms
from .models import Chef, Post, Category, Product, ProductQuantity, CookingStep


class ChefRegistrationForm(forms.ModelForm):
    class Meta:
        model = Chef
        fields = ['username', 'nick_name', 'password', 'email', 'phone', 'about_me']
        labels = {'username': 'Логин',
                  'nick_name': 'Имя',
                  'password': 'пароль',
                  'email': 'электронная почта',
                  'phone': 'телефон',
                  'about_me': 'расскажите о себе'}
        exclude = ['last_login']

    username = forms.CharField(label='Логин для входа', max_length=10, required=True,
                                widget=forms.TextInput(attrs={'placeholder': 'укажите ваш логин'}))
    nick_name = forms.CharField(label='Подпись', max_length=20, required=True,
                                widget=forms.TextInput(attrs={'placeholder': 'укажите ваше имя'}))

    password = forms.CharField(widget=forms.PasswordInput())

    def save(self, commit=True):
        user = super(ChefRegistrationForm, self).save(commit=False)
        user.last_login = None
        if commit:
            user.save()
        return user


class PostForm(forms.ModelForm):
    category_id = forms.ModelChoiceField(queryset=Category.objects.all(), to_field_name='name')

    class Meta:
        model = Post
        fields = ['name', 'description', 'cooking_time', 'images', 'category_id']

    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields['category_id'].label_from_instance = lambda obj: "%s" % obj.name


class CookingStepForm(forms.ModelForm):
    class Meta:
        model = CookingStep
        fields = ['description', 'images']


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description']


class ProductQuantityForm(forms.ModelForm):
    MEASUREMENT_CHOICES = [
        ('кг', 'килограмм'),
        ('литр', 'литр'),
        ('грамм', 'грамм'),
        ('столовая ложка', 'столовая ложка'),
        ('стакан', 'стакан'),
        ('чайная ложка', 'чайная ложка')
    ]

    measurement = forms.ChoiceField(choices=MEASUREMENT_CHOICES)
    product_id = forms.ModelChoiceField(queryset=Product.objects.all(), empty_label=None, to_field_name='name', label='Продукт')

    class Meta:
        model = ProductQuantity
        fields = ['product_id', 'count', 'measurement']


class EditPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['name', 'description', 'cooking_time', 'images', 'category_id']

myapp/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from django.views.generic import TemplateView
from django.contrib.auth import login
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import Chef, Product, Category, Post, ProductQuantity, CookingStep
from .forms import ChefRegistrationForm, PostForm, ProductForm, ProductQuantityForm, CookingStepForm, EditPostForm
from django.contrib.auth.models import User
from django.contrib.auth.hashers import make_password
from django.core.exceptions import ObjectDoesNotExist
from random import sample
from django.utils import timezone

default_value = timezone.now


def home(request):
    recipes = Post.objects.all()
    random_recipes = sample(list(recipes), min(len(recipes), 5))  # Выбираем 5 случайных рецептов или меньше, если их меньше 5
    text_html = """
    <h1>Добро пожаловать на сайт!</h1>
    <p>Здесь собраны рецепты из простых продуктов, которые обычно входят в диетическое питание.</p>
    """
    return render(request, 'index.html', {'content': text_html, 'random_recipes': random_recipes})


def category_list(request):
    categories = Category.objects.all()
    return render(request, 'categories.html', {'categories': categories})


def category_recipes(request, category_id):
    category = get_object_or_404(Category, id=category_id)
    recipes = Post.objects.filter(category_id=category)
    return render(request, 'category_recipes.html', {'category': category, 'recipes': recipes})


def recipe_details(request, recipe_id):
    recipe = get_object_or_404(Post, id=recipe_id)
    cooking_steps = CookingStep.objects.filter(post_id=recipe)
    product_quantities = ProductQuantity.objects.filter(post_id=recipe)
    return render(request, 'recipe_details.html',
                  {'recipe': recipe, 'cooking_steps': cooking_steps, 'product_quantities': product_quantities})


def register_chef(request):
    if request.method == 'POST':
        form = ChefRegistrationForm(request.POST)
        if form.is_valid():
            user_data = form.cleaned_data
            new_user = Chef.objects.create_user(
                username=user_data['username'],
                email=user_data['email'],
                password=make_password(user_data['password'])
            )
            new_user.save()
            login(request, new_user)
            return redirect('/')
    else:
        form = ChefRegistrationForm()
    return render(request, 'registration.html', {'form': form})


@login_required
def add_recipe(request):
    if request.method == 'POST':
        post_form = PostForm(request.POST, request.FILES)
        if post_form.is_valid():
            post = post_form.save(commit=False)
            current_user = request.user
            post.chef_id = current_user
            post.save()
            return redirect('add_product_to_recipe', post_id=post.id)
    else:
        post_form = PostForm()
    return render(request, 'add_recipe.html', {'post_form': post_form})


@login_required
def add_product_to_recipe(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == 'POST':
        product_quantity_form = ProductQuantityForm(request.POST)
        if product_quantity_form.is_valid():
            product_quantity = product_quantity_form.save(commit=False)
            product_name = request.POST.get('product_id')
            try:
                product = Product.objects.get(name=product_name)
            except Product.DoesNotExist:
                product_quantity_form.add_error('product_id', 'Выберите существующий продукт из списка.')
                return render(request, 'add_product_to_recipe.html', {'product_quantity_form': product_quantity_form})
            product_quantity.product_id = product
            product_quantity.post_id = post
            product_quantity.save()
            if "add_product" in request.POST:
                return redirect('add_product_to_recipe', post_id=post_id)
            elif "add_steps" in request.POST:
                return redirect('add_steps_to_recipe', post_id=post_id)
    else:
        product_quantity_form = ProductQuantityForm()
    return render(request, 'add_product_to_recipe.html', {'product_quantity_form': product_quantity_form})


@login_required
def add_steps_to_recipe(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == 'POST':
        cooking_step_form = CookingStepForm(request.POST, request.FILES)
        if cooking_step_form.is_valid():
            cooking_step = cooking_step_form.save(commit=False)
            cooking_step.post_id = post
            cooking_step.save()
            if "add_product" in request.POST:
                return redirect('add_steps_to_recipe',
                            post_id=post_id)
            elif "add_steps" in request.POST:
                return redirect('/')
    else:
        cooking_step_form = CookingStepForm()
    return render(request, 'add_steps_to_recipe.html', {'cooking_step_form': cooking_step_form})


# @login_required
# def edit_recipe(request, post_id):
#     post = get_object_or_404(Post, id=post_id)
#     if request.method == 'POST':
#         form = EditPostForm(request.POST, request.FILES, instance=post)
#         if form.is_valid():
#             form.save()
#             return redirect('recipe_details', recipe_id=post_id)
#     else:
#         form = EditPostForm(instance=post)
#     return render(request, 'edit_recipe.html', {'form': form, 'post': post})

def edit_recipe(request, recipe_id):
    recipe = get_object_or_404(Post, id=recipe_id)
    form = None
    if request.user == recipe.chef_id:
        print(1)
        if request.method == 'POST':
            print(2)
            form = EditPostForm(request.POST, request.FILES, instance=recipe)
            if form.is_valid():
                print(3)
                form.save()
                return redirect('recipe_detail',
                                recipe_id=recipe_id)  # Предполагая, что у вас есть view для деталей рецепта
        else:
            form = EditPostForm(instance=recipe)
    else:
        return HttpResponse('У вас нет прав для редактирования этого рецепта.')

    return render(request, 'edit_recipe.html', {'form': form, 'recipe': recipe})


def chef_recipes(request, chef_id):
    chef_posts = Post.objects.filter(chef_id=chef_id)
    return render(request, 'chef_recipes.html', {'chef_posts': chef_posts})


def my_recipes(request):
    current_user = request.user
    chef_posts = Post.objects.filter(chef_id=current_user.id)
    return render(request, 'my_recipes.html', {'chef_posts': chef_posts})

def all_recipes(request):
    all_posts = Post.objects.all()
    return render(request, 'all_recipes.html', {'all_posts': all_posts})


@login_required
def recipe_detail(request, recipe_id):
    recipe = get_object_or_404(Post, id=recipe_id)

    # Получаем все продукты и шаги, связанные с данным рецептом
    products = ProductQuantity.objects.filter(post_id=recipe)
    steps = CookingStep.objects.filter(post_id=recipe)

    if request.method == 'POST':
        # Обработка формы продуктов
        product_quantity_form = ProductQuantityForm(request.POST)
        if product_quantity_form.is_valid():
            product_quantity = product_quantity_form.save(commit=False)
            product_name = request.POST.get('product_id')
            try:
                product = Product.objects.get(name=product_name)
            except Product.DoesNotExist:
                product_quantity_form.add_error('product_id', 'Выберите существующий продукт из списка.')
                return render(request, 'recipe_detail.html', {'recipe': recipe, 'products': products, 'steps': steps,
                                                              'product_quantity_form': product_quantity_form})
            product_quantity.product_id = product
            product_quantity.post_id = recipe
            product_quantity.save()

        # Обработка формы шагов
        cooking_step_form = CookingStepForm(request.POST, request.FILES)
        if cooking_step_form.is_valid():
            cooking_step = cooking_step_form.save(commit=False)
            cooking_step.post_id = recipe
            cooking_step.save()

        return redirect('recipe_detail', recipe_id=recipe_id)  # Перенаправляем на страницу с обновленными данными

    # Если это GET запрос, просто отображаем данные
    product_quantity_form = ProductQuantityForm()
    cooking_step_form = CookingStepForm()

    return render(request, 'recipe_detail.html', {'recipe': recipe, 'products': products, 'steps': steps,
                                                  'product_quantity_form': product_quantity_form,
                                                  'cooking_step_form': cooking_step_form})

myapp/templates/add_product_to_recipe.html
{% extends 'base.html' %}
{% block content %}
    <h2>Добавление продукта к рецепту "{{ post.title }}"</h2>
    <form method="post">
        {% csrf_token %}
        {{ product_quantity_form.as_p }}
        <button type="submit" name="add_product">Добавить еще один продукт</button>
        <button type="submit" name="add_steps">Перейти к описанию шагов</button>
    </form>
{% endblock %}

myapp/templates/add_recipe.html
{% extends 'base.html' %}
{% block content %}
    <h2>Добавление рецепта</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ post_form.as_p }}
        <button type="submit">Добавить рецепт</button>
    </form>
{% endblock %}

myapp/templates/add_steps_to_recipe.html
{% extends 'base.html' %}
{% block content %}
    <h2>Добавление шага к рецепту "{{ post.title }}"</h2>
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ cooking_step_form.as_p }}
        <button type="submit" name="add_product">Добавить еще один шаг приготовления</button>
        <button type="submit" name="add_steps">Завершить</button>
</form>
{% endblock %}

myapp/templates/all_recipes.html
{% extends 'base.html' %}
{% block content %}
    <h1>Все рецепты</h1>
    {% for post in all_posts %}
        <div class="info_page_text">
            <h3><a href="{% url 'recipe_details' post.id %}">{{ post.name }}</a></h3>
            <p>{{ post.description }}</p>
            {% if user.is_authenticated and user.id == post.chef_id.id %}
                <a href="{% url 'edit_recipe' post.id %}">Редактировать рецепт</a>
            {% endif %}
        </div>
    {% endfor %}
{% endblock %}

myapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Рецепты для диеты{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'styles/style.css' %}">
</head>
<body>
    <header class="header">
                <a href="{% url 'home' %}" class="header_block_menu_item">Главная</a>
                <a href="{% url 'category_list' %}" class="header_block_menu_item">Категории</a>
                <a href="{% url 'all_recipes' %}" class="header_block_menu_item no_mobile">Все рецепты</a>
                {% if user.is_authenticated %}
                    <a href="{% url 'add_recipe' %}" class="header_block_menu_item">Добавить рецепт</a>
                    <a href="{% url 'my_recipes' %}" class="header_block_menu_item no_mobile">Мои рецепты</a>
                   <form action="{% url 'logout' %}" method="post">
                       {% csrf_token %}
                       <button type="submit" class="header_block_menu_button">Выход</button>
                   </form>
                {% else %}
                    <a href="{% url 'login' %}" class="header_block_menu_item">Вход</a>
               {% endif %}
    </header>

    <main>
        {% block content %}

        {% endblock %}
    </main>

    <footer class="footer">
        <p>© 2024  Totskaya O.V.</p>
    </footer>
</body>
</html>

myapp/templates/categories.html
{% extends 'base.html' %}
{% block content %}
    <h1>Категории рецептов</h1>
    <ul>
        {% for category in categories %}
            <li>
                <h1 class="category"><a href="{% url 'category_recipes' category.id %}">{{ category.name }}</a></h1>
                <div class="description"><p>{{ category.description }}</p></div>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

myapp/templates/category_recipes.html
{% extends 'base.html' %}
{% block content %}
    <h1>{{ category.name }}</h1>
    <p>{{ category.description }}</p>
    
    <h2>Рецепты в этой категории:</h2>
    <div class="info_page_text">
        <ul>
            {% for recipe in recipes %}
                <li>
                    <h3><a href="{% url 'recipe_details' recipe.id %}">{{ recipe.name }}</a></h3>
                    <p>{{ recipe.description }}</p>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

myapp/templates/chef_recipes.html
{% extends 'base.html' %}
{% block content %}
    <h1>Recipes by {{ chef_posts.first.chef_id.username }}</h1>
    {% for post in chef_posts %}
        <h2>{{ post.name }}</h2>
        <p>{{ post.description }}</p>
        <h3>Ingredients:</h3>
        <ul>
            {% for product_quantity in post.productquantity_set.all %}
                <li>{{ product_quantity.count }} {{ product_quantity.get_measurement_display }} of {{ product_quantity.product_id.name }}</li>
            {% endfor %}
        </ul>
        <h3>Cooking Steps:</h3>
        <ol>
            {% for step in post.cookingstep_set.all %}
                <li>{{ step.description }}</li>
            {% endfor %}
        </ol>
    {% endfor %}
{% endblock %}

myapp/templates/edit_recipe.html
{#{% extends 'base.html' %}#}
{#{% block content %}#}
{##}
{#    <form method="post" enctype="multipart/form-data">#}
{#       {% csrf_token %}#}
{#       {{ form.as_p }}#}
{#       <button type="submit">Сохранить изменения</button>#}
{#   </form>#}
{##}
{#{% endblock %}#}

{% extends 'base.html' %}

{% block content %}
    <h2>Редактирование рецепта</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить изменения</button>
    </form>
{% endblock %}

myapp/templates/index.html
{% extends 'base.html' %}
{% block content %}
    <div class="info_page">
        <img src="static/images/ketogenic-low-carbs-diet-food-selection-white-wall.jpg" class="info_page_img">
        <div class="info_page_text">{{ content | safe }}</div>
    </div>

    <section class="info_random_page">
        <div class="info_random_page_title">
            <h2>Шеф, сегодня в меню блюда-дня</h2>
        </div>
        <div class="info_random_page_recipe_list">
            <ul>
                {% for recipe in random_recipes %}
                    <li class="description_text">
                        <a href="{% url 'recipe_details' recipe.id %}">{{ recipe.name }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </section>
{% endblock %}

myapp/templates/my_recipes.html
{% extends 'base.html' %}
{% block content %}
    <h1>Рецепты от шеф повара {{ chef_posts.first.chef_id.username }}</h1>
    {% for post in chef_posts %}
        <div class="info_page_text">
            <h3><a href="{% url 'recipe_details' post.id %}">{{ post.name }}</a></h3>
            <p>{{ post.description }}</p>
            <a href="{% url 'edit_recipe' post.id %}">Редактировать рецепт</a>
        </div>
    {% endfor %}
{% endblock %}

myapp/templates/recipe_detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="info_page">
        {% if recipe.images %}
            <img src="{{ recipe.images.url }}" alt="{{ recipe.name }}" class="recipe_img">
        {% endif %}
        <div class="info_page_text">
            <h1>{{ recipe.name }}</h1>
            <p>{{ recipe.description }}</p>
        </div>
    </div>
    <div class="description_text">
        <h2>Ингредиенты:</h2>
        <ul>
            {% for product_quantity in products %}
                <li>{{ product_quantity.product_id.name }}: {{ product_quantity.count }} {{ product_quantity.get_measurement_display }}</li>
            {% endfor %}
        </ul>
        
        <h2>Шаги приготовления:</h2>
        <ol>
            {% for step in steps %}
                <li>
                    <h3>Шаг {{ forloop.counter }}</h3>
                    <p>{{ step.description }}</p>
                    {% if step.images %}
                        <img src="{{ step.images.url }}" alt="Step {{ forloop.counter }}">
                    {% endif %}
                </li>
            {% endfor %}
        </ol>
        
        {% if user.is_authenticated and user.id == recipe.chef_id.id %}
            <h3>Добавить продукт:</h3>
            <form method="post">
                {% csrf_token %}
                {{ product_quantity_form.as_p }}
                <button type="submit">Добавить продукт</button>
            </form>
            
            <h3>Добавить шаг приготовления:</h3>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ cooking_step_form.as_p }}
                <button type="submit">Добавить шаг</button>
            </form>
        {% endif %}
    </div>
{% endblock %}

myapp/templates/recipe_details.html
{% extends 'base.html' %}
{% block content %}
    <div class="info_page">
        {% if recipe.images %}
            <img src="{{ recipe.images.url }}" alt="{{ recipe.name }}" class="recipe_img">
        {% endif %}
        <div class="info_page_text">
            <h1>{{ recipe.name }}</h1>
            <p>{{ recipe.description }}</p>
        </div>
    </div>
    <div class="description_text">
    <p>Ингредиенты:<br>
    {% for product_quantity in product_quantities %}
        - {{ product_quantity.product_id.name }}: {{ product_quantity.count }} {{ product_quantity.get_measurement_display }}<br>
    {% endfor %}</p>

    <h2>Шаги приготовления:</h2>
    <ul>
        {% for step in cooking_steps %}
            <li class="description_list">
                <h3>Шаг {{ forloop.counter }}</h3>
                <p>{{ step.description }}</p>
                {% if step.images %}
                    <img src="{{ step.images.url }}" alt="Step {{ forloop.counter }}">
                {% endif %}
            </li>
        {% endfor %}
    </ul>
    {% if user.is_authenticated and user.id == recipe.chef_id %}
        <a href="{% url 'edit_recipe' recipe.id %}">Редактировать рецепт</a>
    {% endif %}
    </div>
{% endblock %}

myapp/templates/registration.html
{% extends 'base.html' %}

{% block title %}
    Регистрация шеф-повара - RecipesHub
{% endblock %}

{% block content %}
    {% load static %}
    <div class="info_page">
    <img src="{% static 'images/chef.jpg' %}" class="registration_img">
        <div class="info_page_text">
            <h1>Регистрация шеф-повара</h1>

            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Зарегистрироваться</button>
            </form>
        </div>
    </div>
{% endblock %}